import { Router } from 'express';
import { Room } from '../models/Room.js';
import { Schedule } from '../models/Schedule.js';
import { User } from '../models/User.js';
import { AuditService } from '../services/audit.service.js';
import { authenticate, authorize } from '../middleware/auth.middleware.js';
import XLSX from 'xlsx';
import type { Request, Response, NextFunction } from 'express';

const router = Router();

// Helper to convert HH:MM to duration in hours
function getDurationInHours(startTime: string, endTime: string): number {
  const [startH, startM] = startTime.split(':').map(Number);
  const [endH, endM] = endTime.split(':').map(Number);
  const startMin = startH * 60 + startM;
  const endMin = endH * 60 + endM;
  return Math.max(0, (endMin - startMin) / 60);
}

// Common calculations function
async function calculateStats(startDate: string, endDate: string) {
  const rooms = await Room.find().lean();
  const schedules = await Schedule.find({
    date: { $gte: startDate, $lte: endDate }
  }).lean();

  const start = new Date(startDate);
  const end = new Date(endDate);
  const timeDiff = end.getTime() - start.getTime();
  const numDays = Math.max(1, Math.round(timeDiff / (1000 * 60 * 60 * 24)) + 1);
  const availableHoursPerRoom = numDays * 12; // 8:00 AM - 8:00 PM (12 hours)

  const roomStatsMap = new Map(
    rooms.map((r) => [
      r._id.toString(),
      {
        roomId: r._id.toString(),
        roomNumber: r.roomNumber,
        building: r.building,
        totalBookings: 0,
        totalHoursUsed: 0,
        utilizationPercentage: 0
      }
    ])
  );

  for (const s of schedules) {
    const roomIdStr = s.roomId.toString();
    const stats = roomStatsMap.get(roomIdStr);
    if (stats) {
      stats.totalBookings += 1;
      stats.totalHoursUsed += getDurationInHours(s.startTime, s.endTime);
    }
  }

  let totalHoursUsed = 0;
  let totalBookings = 0;
  const roomStatsList = Array.from(roomStatsMap.values());

  for (const stats of roomStatsList) {
    stats.totalHoursUsed = Math.round(stats.totalHoursUsed * 10) / 10;
    stats.utilizationPercentage = availableHoursPerRoom > 0
      ? Math.min(100, Math.round((stats.totalHoursUsed / availableHoursPerRoom) * 100))
      : 0;
    totalHoursUsed += stats.totalHoursUsed;
    totalBookings += stats.totalBookings;
  }

  // Find most and least used rooms
  let mostUsedRoom = null;
  let leastUsedRoom = null;

  if (roomStatsList.length > 0) {
    mostUsedRoom = roomStatsList[0];
    leastUsedRoom = roomStatsList[0];

    for (const stats of roomStatsList) {
      if (stats.totalHoursUsed > mostUsedRoom.totalHoursUsed) {
        mostUsedRoom = stats;
      }
      if (stats.totalHoursUsed < leastUsedRoom.totalHoursUsed) {
        leastUsedRoom = stats;
      }
    }
  }

  return {
    summary: {
      totalBookings,
      totalHoursUsed: Math.round(totalHoursUsed * 10) / 10,
      mostUsedRoom: mostUsedRoom ? { roomNumber: mostUsedRoom.roomNumber, building: mostUsedRoom.building, hoursUsed: mostUsedRoom.totalHoursUsed } : null,
      leastUsedRoom: leastUsedRoom ? { roomNumber: leastUsedRoom.roomNumber, building: leastUsedRoom.building, hoursUsed: leastUsedRoom.totalHoursUsed } : null,
    },
    roomStats: roomStatsList
  };
}

// GET /api/analytics - Fetch aggregate statistics
router.get('/', authenticate, authorize('superadmin', 'admin'), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { startDate, endDate } = req.query;
    if (!startDate || !endDate) {
      res.status(400).json({ success: false, message: 'startDate and endDate are required' });
      return;
    }

    const stats = await calculateStats(startDate as string, endDate as string);

    // Audit log analytics viewing
    await AuditService.log('ANALYTICS_VIEW', req.user!.userId, 'analytics', null, {
      startDate,
      endDate
    });

    res.json({ success: true, ...stats });
  } catch (error) {
    next(error);
  }
});

// GET /api/analytics/export - Export Excel utilization report
router.get('/export', authenticate, authorize('superadmin', 'admin'), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { startDate, endDate, rangeLabel } = req.query;
    if (!startDate || !endDate) {
      res.status(400).json({ success: false, message: 'startDate and endDate are required' });
      return;
    }

    const stats = await calculateStats(startDate as string, endDate as string);
    const user = await User.findById(req.user!.userId).lean();
    const userName = user ? user.name : 'Unknown Admin';

    // Format metadata block
    const formattedDate = new Date().toLocaleDateString('en-US', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    });

    const metadata = [
      ['Generated On:', formattedDate],
      ['Generated By:', userName],
      ['Date Range:', (rangeLabel as string) || `${startDate} to ${endDate}`],
      [] // Blank line separator
    ];

    // Headers and Rows
    const headers = ['Room Number', 'Building', 'Total Bookings', 'Total Hours Used', 'Utilization Percentage'];
    const rows = stats.roomStats.map((item) => [
      item.roomNumber,
      item.building,
      item.totalBookings,
      item.totalHoursUsed,
      `${item.utilizationPercentage}%`
    ]);

    // Create workbook & worksheet
    const ws = XLSX.utils.aoa_to_sheet([...metadata, headers, ...rows]);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Room Utilization');

    // Generate buffer
    const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });

    // Audit log analytics export
    await AuditService.log('ANALYTICS_EXPORT', req.user!.userId, 'analytics', null, {
      startDate,
      endDate
    });

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename=room_utilization_${startDate}_to_${endDate}.xlsx`);
    res.send(buf);
  } catch (error) {
    next(error);
  }
});

export default router;
